### ISSUE TITLE
FEP tutorial for protein-protein binding

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpaceTutorials#10]
Hi guys, thanks for your series of FEP tutorials, BioSimSpace is a powerful tool to assess the protein-small molecule ligand binding affinities. 
Recently, I'm trying to model protein-protein binding by free energy calculations, which were used to optimize antibody potency.  After some search, I found there was no such information related to that topic in BioSimSpaces' materials. I would like to ask: 

1. Would that be feasible for the current version of BioSimSpace? 
2. If it's not feasible yet, would that capability be added in the future? 

Thanks~

**Comment by jmichel80** [comment]
Hi @kexul protein FEP would certainly be feasible with Gromacs has a back-end, but we do not support this feature at the moment. SOMD doesn't support this feature currently, and neither does the AMBER FEP implementation (I think). Eventually we plan to have a range of free energy protocols in BioSimSpace plugging in different backends but I don't think protein FEP will be implemented by us soon.

**Comment by kexul** [comment]
Get it! Thanks for the information.
