### ISSUE TITLE
ABFE

### ISSUE THREAD

**Issue by rubinanoor9** [michellab/BioSimSpaceTutorials#14]
I have performed funnel metadynamics simulation using the Biosimspace. During ABFE calculation, I am a little bit confused.
As in the tutorial file "https://github.com/michellab/BioSimSpaceTutorials/blob/main/02_funnel_metad/03_bss-fun-metad-analysis.ipynb"

mentioning the:

# the last 0.5 nm of the projection CV are between indices -75 to -25
free_nrg_floats = [ i.kj_per_mol().magnitude() for i in free_nrg0[1][-75:-25] ]

I am not understanding this line. What would be the indices? Mean how we know about the indices range from our data.
I am looking forward to hearing from you.
Thanks in advance

**Comment by lohedges** [comment]
Hi there,

I believe that this was just inferred by looking at the plots above the section that you are referring to. There is an object `free_nrg0` that contains the x and y values for the free energy calculation. You can simply query the entries in `free_nrg0[0]` to work out what indices you need, cross-referencing with the graph to see where the free energy estimate has plateaued.

In general, I think it is quite hard to automate this step, hence the manual specification for the required indices.

Cheers.
