### ISSUE TITLE
making all tutorials uniform using a common style guide

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpaceTutorials#19]
@lohedges, @annamherz @jmichel80 @fjclark @AdeleHardie @dlukauskis, I have created a style guide here: https://github.com/michellab/BioSimSpaceTutorials/blob/main/Style_guide.ipynb

Can you look over it and let me know what you think. It would be good to converge on a style guide and then implement this for each tutorial so that they do look uniform.

**Comment by ppxasjsm** [comment]
Do you have any thoughts on this? If so would be great to start implementing this?

**Comment by jmichel80** [comment]
I like the style guide you put together !

**Comment by AdeleHardie** [comment]
I like it as well! Are we hoping to have "exercises" for the tutorial, or is the format just part of the overall style guide and the BSS tutorial is more "follow along"?

**Comment by jmichel80** [comment]
Exercises are not compulsory, some of the tutorials we put together (e.g. the FEP ones) have parts where delegates are prompted to complete cells in notebooks.

**Comment by ppxasjsm** [comment]
> I like the style guide you put together !

Great :)!

Yes exercises are not compulsory, but the tutorials that have them should add them. And I assume everyone is also ok with no extra solutions notebook to avoid double maintenance right? 

I'll adapt it for the intro to alchemisry tutorial to follow the guide, then you have a template and we can use this as an example for the others.  I don't think much change is needed to be honest. Is everyone ok to adapt the tutorial they wrote? I can probably help with some of the others too..

**Comment by annamherz** [comment]
> And I assume everyone is also ok with no extra solutions notebook to avoid double maintenance right?

yep! I think that is a lot neater, I've changed them for the fep ones.
