### ISSUE TITLE
Issues 01_intro to alchemistry

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpaceTutorials#22]
Some suggested fixes:

In section 2 merged systems maybe link to 7.1.1 directly:
- There are different topologies, and which is used, single or dual, depends largely on the software. For more information, check the <span style="color:pink">further reading </span>: 7.1.1 (Topologies).

**Comment by ppxasjsm** [comment]
Do you mean the alchemical best practices paper here @annamherz:

Are there any off-diagonals that are less than 0.03?
Further reading : 8.5 (overlap matrix)

**Comment by ppxasjsm** [comment]
Overlap section can do with a bit of tidying up!

**Comment by annamherz** [comment]
> Overlap section can do with a bit of tidying up!

I've added some example images and an exercise 😊
