### ISSUE TITLE
Will there by any tutorials for different FEP protocols such as non-equilibrium FEP or Hamiltonian Replica Exchange?

### ISSUE THREAD

**Issue by noahharrison64** [michellab/BioSimSpaceTutorials#27]
Hi,

I just discovered this repo and look forward to having a play around with BioSimSpace. I was hoping to conduct some non-eq FEP calculations such as those detailed in [this paper](https://pubs.rsc.org/en/content/articlelanding/2020/sc/c9sc03754c). I wonder whether this will be possible using your API. It's my understanding that during the production stage, there needs to be functionality to change lambda values over the course of the short transition simulations between state A and state B. And then during the analysis stage implementations of the Crooks fluctuation and Jarzynski theorems are required. 

I'd also be interested in eventually attempting to implement Hamiltonian Replica Exchange
(HREX) as a method for eq-FEP. 

Are there any considerations for making these non-canonical FEP protocols easily implemented in BioSimSpace? Or would anyone have any pointers for how to go about implementing such protocols with existing architecture?

Thanks,
Noah

**Comment by jmichel80** [comment]
Hi, 

Currently the API doesn't support setup of non-equilibrium FEP calculations and there isn't support for a generic HREX interface but it is possible with a little bit of work to setup inputs with BSS,  run HREX simulations with a chosen engine outside of the framework and load back the trajectories for analysis.   

We are currently consolidating various branches that implement different flavours of FEP using different engines. At the moment it is probably difficult to develop this part of the codebase without prior knowledge. Most of the changes required would be in https://github.com/michellab/BioSimSpace/tree/devel/python/BioSimSpace/FreeEnergy and https://github.com/michellab/BioSimSpace/tree/devel/python/BioSimSpace/Process

Julien

**Comment by noahharrison64** [comment]
Hi Julien,

Looking forward to future versions that may implement these natively, in the meantime I'll look into running HREX independently of BSS simulation!

Many thanks,
Noah
