### ISSUE TITLE
ff14SB issue

### ISSUE THREAD

**Issue by amarye** [michellab/BioSimSpaceTutorials#30]
I got an error for ff14SB parametersization.
Could you please help me to solve this issue?
![Screenshot from 2024-01-11 10-44-19](https://github.com/michellab/BioSimSpaceTutorials/assets/55770700/2aa1cd77-6141-4fff-8ffd-b5566b1256d1)

**Comment by jmichel80** [comment]
Hi @amarye could you repeat this using the code hosted at https://github.com/OpenBioSim/biosimspace_tutorials ? The tutorials suite on the michellab  repository is deprecated and no longer maintained

**Comment by lohedges** [comment]
@jmichel80: When I get a chance I'll actually run the current notebook and will add a fix if necessary.

**Comment by amarye** [comment]
Thank you very much. It is working. But I got another errors.

![Screenshot from 2024-01-12 15-37-48](https://github.com/michellab/BioSimSpaceTutorials/assets/55770700/18b84ef3-871e-4490-801d-931f16ab7d84)

also
![Screenshot from 2024-01-12 15-37-17](https://github.com/michellab/BioSimSpaceTutorials/assets/55770700/f2dde5ab-fac8-45ae-bd6a-baea75006249)

**Comment by lohedges** [comment]
@jmichel80: Just to say that I've checked the new tutorial suite and everything is okay. The fix that I proposed above is in a different place, hence why I didn't spot it first time around.

**Comment by amarye** [comment]
> Hi @amarye could you repeat this using the code hosted at https://github.com/OpenBioSim/biosimspace_tutorials ? The tutorials suite on the michellab repository is deprecated and no longer maintained

I have used this tutorial, but I am still facing the above problems.

**Comment by jmichel80** [comment]
hi @amarye  - can you post an new issue here https://github.com/OpenBioSim/biosimspace_tutorials/issues , please describe in your new issue how you installed the tutorials suite

**Comment by lohedges** [comment]
This is because you aren't using the latest version of BioSimSpace. I'm _assuming_ that you have an outdated copy, or one from the `michellab` conda channel, not the from `OpenBioSim`.

Looking at the latest code, the line where your error is occurring is different, i.e. [here](https://github.com/OpenBioSim/biosimspace/blob/4817660036f2bd133986a912309ede9f172d3179/python/BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py#L1136-L1142)

```python
    for step in _np.arange(lower_wall, upper_wall + vec_step, vec_step):
        # iterate around a circle with its radius defined by the sigmoid function
        radius = (wall_width / (1 + _np.exp(beta_cent * (step - s_cent)))) + wall_buffer
        for angle in _np.arange(-_np.pi, _np.pi, 2 * _np.pi / n_angle_samples):
            # Calculate parametric functions for this specific case
            # https://math.stackexchange.com/questions/73237/parametric-equation-of-a-circle-in-3d-space
            # Generate pseudoatoms along the axis.
```

In the latest code were are calling `.value()` on the vectors to get the raw float when computing the CoM, i.e. [here](https://github.com/OpenBioSim/biosimspace/blob/4817660036f2bd133986a912309ede9f172d3179/python/BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py#L1068C1-L1082C37).

```python
    for atom in atoms0:
        try:
            com0 += atoms[atom]._sire_object.property(coordinates)
        except:
            raise ValueError(f"Could not obtain coordinates for atom index '{atom}'!")
    com0 /= len(atoms0)
    com0 = [x.value() for x in com0]


    for atom in atoms1:
        try:
            com1 += atoms[atom]._sire_object.property(coordinates)
        except:
            raise ValueError(f"Could not obtain coordinates for atom index '{atom}'!")
    com1 /= len(atoms1)
    com1 = [x.value() for x in com1]
```

Originally Sire Vector objects didn't have units and it was implicitly assumed that, when referring to positions, the represented Angstrom.

**Comment by amarye** [comment]
> This is because you aren't using the latest version of BioSimSpace. I'm _assuming_ that you have an outdated copy, or one from the `michellab` conda channel, not the from `OpenBioSim`.
> 
> Looking at the latest code, the line where your error is occurring is different, i.e. [here](https://github.com/OpenBioSim/biosimspace/blob/4817660036f2bd133986a912309ede9f172d3179/python/BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py#L1136-L1142)
> 
> ```python
>     for step in _np.arange(lower_wall, upper_wall + vec_step, vec_step):
>         # iterate around a circle with its radius defined by the sigmoid function
>         radius = (wall_width / (1 + _np.exp(beta_cent * (step - s_cent)))) + wall_buffer
>         for angle in _np.arange(-_np.pi, _np.pi, 2 * _np.pi / n_angle_samples):
>             # Calculate parametric functions for this specific case
>             # https://math.stackexchange.com/questions/73237/parametric-equation-of-a-circle-in-3d-space
>             # Generate pseudoatoms along the axis.
> ```
> 
> In the latest code were are calling `.value()` on the vectors to get the raw float when computing the CoM, i.e. [here](https://github.com/OpenBioSim/biosimspace/blob/4817660036f2bd133986a912309ede9f172d3179/python/BioSimSpace/Metadynamics/CollectiveVariable/_funnel.py#L1068C1-L1082C37).
> 
> ```python
>     for atom in atoms0:
>         try:
>             com0 += atoms[atom]._sire_object.property(coordinates)
>         except:
>             raise ValueError(f"Could not obtain coordinates for atom index '{atom}'!")
>     com0 /= len(atoms0)
>     com0 = [x.value() for x in com0]
> 
> 
>     for atom in atoms1:
>         try:
>             com1 += atoms[atom]._sire_object.property(coordinates)
>         except:
>             raise ValueError(f"Could not obtain coordinates for atom index '{atom}'!")
>     com1 /= len(atoms1)
>     com1 = [x.value() for x in com1]
> ```
> 
> Originally Sire Vector objects didn't have units and it was implicitly assumed that, when referring to positions, the represented Angstrom.

It is 2023.2.0

**Comment by lohedges** [comment]
The latest version of the code is 2023.5.0. As I guessed, it appears that you are using an old copy of the code from the michellab conda channel. I've posted more on the other thread.

**Comment by amarye** [comment]
It is working now. Thanks
